name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Deploy
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_NAME: ${{ secrets.BOT_NAME }}
        run: |
          ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_HOST << 'EOF'
          cd /home/belnitskii/TelegramBotCB
          mvn clean package -DskipTests  # Пересобираем JAR-файл
          docker-compose down || true
          docker-compose build --no-cache  # Пересобираем образ без кеша
          docker-compose up -d
          EOF